name=kitchensink-tf-psa-crypto
version=1.0.0
author=dbb789
maintainer=dbb789
sentence=mbedTLS TF-PSA-Crypto library repacked for Arduino IDE
paragraph=
category=Uncategorized
url=https://github.com/dbb789
architectures=*
